#!/bin/bash

TREE=/tmp/leap-15.4-image.tar

host=$1
if [ -z "$host" ]; then
	echo "Missing host IP address" >&2
	exit 1
fi

if ! ping -c1 $host; then
	echo "Are you sure that $host is a valid IP address?" >&2
	exit 1
fi

ssh vagrant@$host "cd /; sudo tar -C / -cf - bin boot/{vmlinuz*,initrd*,System.map*} etc home lib lib64 mnt opt root sbin srv tmp usr var" > $TREE

echo "Created $TREE"
