#!/bin/bash

IMGDIR=./ALP
IMGFLAVOR=SelfInstall_NonTransactional
BUILD_BASE=/tmp/myimage
BUILD_ROOT="$BUILD_BASE/root"

DEBUG=--debug
REPOS="--set-repo obs://openSUSE:Leap:15.4/standard"
REPOS=

function extra_pkg_args {

	# not working...
	if test -d extra-pkgs; then
		echo -e "--add-repo dir:$PWD/extra-pkgs,rpm-dir"
	fi
}

# PACKAGES=$(extra_pkg_args)

case $1 in
prepare|create|build|obuild)
	verb=$1;;
'')	verb=build;;
*)	echo "Unsupported action \"$1\"" >&2; exit 1;;
esac

logfile="kiwi-${verb}.log"
rm -f $logfile
LOGOPTION="--logfile $logfile"


case $verb in
build)
	$0 prepare && $0 create;;

obuild)
	rm -rf /var/cache/kiwi/packages/da4a5b0de53b179eb79d2dff631b5939
	rm -rf $BUILD_BASE
	kiwi-ng --profile $IMGFLAVOR \
		$DEBUG $LOGOPTION \
		system build \
		--description $IMGDIR \
		$REPOS \
		$PACKAGES \
		--target-dir $BUILD_BASE;;

prepare)
	rm -rf $BUILD_ROOT
	kiwi-ng --profile $IMGFLAVOR \
		$DEBUG $LOGOPTION \
		system prepare \
		--description $IMGDIR \
		--clear-cache \
		$REPOS \
		$PACKAGES \
		--root $BUILD_ROOT;;

create)
	FDE_SCRIPT="$BUILD_BASE/root/usr/share/jeos-firstboot/modules/fde"
	if ! cmp -s firstboot/fde $FDE_SCRIPT; then
		echo "***********"
		echo "FDE firstboot script changed, overwriting"
		cp -v firstboot/fde $FDE_SCRIPT
		echo "***********"
	fi

	kiwi-ng --profile $IMGFLAVOR \
		$DEBUG $LOGOPTION \
		system create \
		--root $BUILD_ROOT \
		--target-dir $BUILD_BASE;;

*)	echo "Action $verb not implemented" >&2;;
esac
