#!/bin/bash
#
# This script starts up a VM using an ALP KVM image
#
# Written by okir@suse.com
#

OKIR_IMG_URL=https://download.opensuse.org/repositories/home:/okir:/FDE/images/
ALP_IMG_URL=https://download.opensuse.org/repositories/SUSE:/ALP/images/

# As long as ALP uses its own buildcert to sign Secure Boot related code,
# KVM needs a special set of SB variables:
UEFI_ALP_VARS_FILE="/usr/share/qemu/ovmf-x86_64-smm-alp-vars.bin"

DEFAULT_IMG_CACHE="/var/tmp/alp-demo"
DEFAULT_VM_NAME="alp-demo"

# This is not true, but allows this demo to run on 15.3 upwards
ALP_OS_VARIANT=opensuse15.3
ALP_OS_VARIANT=opensusetumbleweed


function usage {

	exitval=$1

	cat <<EOF
run-alp [-N vm-name] [-C cache-dir] [img-path]"
  -N vm-name, --name vm-name
        name of the VM to create [default $DEFAULT_VM_NAME]
  -C path, --cachedir path
        specify a directory to hold ALP images [default $DEFAULT_IMG_CACHE]
  --no-fde
  	Run image without full disk encryption
  -f, --force
        if a VM of the given name was created previously, remove it
        without asking for confirmation.
  -p, --persistent
        by default, the VM created by this script will be transient,
        i.e. it will be deleted when you exit virt-viewer. If you want
        to create a persisent VM instead, use the -p flag. You will
        be able to start, stop and delete the VM using virt-manager.

img-path can be used to specify the name of an image to run.
By default, the script will try to run the current ALP-VM image from the
SUSE Open Build Service.

EOF

	exit $exitval
}

opt_vm_name="$DEFAULT_VM_NAME"
opt_cache_dir=
opt_force=false
opt_persistent=false
opt_sb_auth=opensuse
opt_img_flavor=kvm_encrypted

eval set -- $(getopt -l no-fde,sb-auth:,cachedir:,name:,force,persistent,help,okir A:C:N:fh "$@")
while [ $# -gt 0 ]; do
	opt=$1; shift
	case $opt in
	--no-fde)
		opt_img_flavor=kvm;;
	-A|--sb-auth)
		opt_sb_auth=$1; shift;;
	-C|--cachedir)
		opt_cache_dir=$1; shift;;
	-N|--name)
		opt_vm_name=$1; shift;;
	-f|--force)
		opt_force=true;;
	-p|--persistent)
		opt_persistent=true;;
	-h|--help)
		usage 0;;
	--okir)
		ALP_IMG_URL=$OKIR_IMG_URL
		DEFAULT_IMG_CACHE="$DEFAULT_IMG_CACHE/okir"
		opt_sb_auth=alp;;
	--)	break;;
	*)	echo "Unsupported option $opt" >&2
		usage 1;;
	esac
done

if [ -z "$opt_cache_dir" ]; then
	opt_cache_dir="$DEFAULT_IMG_CACHE"
fi

case $(stat -f "$opt_cache_dir" -c %T) in
nfs|nfs4|cifs)
	cat >&2 <<-EOF

	Warning: your image cache is on a remote file system. Consider specifying an
	alternative location using the -C option.

EOF
	: ;;
esac

function identify_image {

	 wget -nv "$ALP_IMG_URL" -O - |
	 	tr '<>' '\012\012' | sed '/^a href="\(.*\)"/!d;s//\1/' |
		grep "ALP-VM.x86_64.*-${opt_img_flavor}-.*"'\.qcow2$' |
		sort -u
}

function download_image {

	declare -g ALP_IMG_LOCAL

	echo "Downloading ALP $opt_img_flavor image from $ALP_IMG_URL"
	echo "to $opt_cache_dir"

	img_name=$(identify_image)
	case $(echo "$img_name" | wc -w) in
	0)	echo "Unable to identify image" >&2
		exit 1;;
	1)	: ;;
	*)	echo "Found more than one image at $ALP_IMG_URL" >&2
		exit 1;;
	esac

	echo "Found image $img_name"
	wget -nv -N -P "$opt_cache_dir" "$ALP_IMG_URL/$img_name" || exit 1

	ALP_IMG_LOCAL="$opt_cache_dir/$img_name"
}

function user_confirm {

	msg="$1"
	while true; do
		echo -n "$msg [y/N]: "
		read word
		case $word in
		[yY])
			return 0;;
		""|[nN])
			return 1;;
		esac
	done
}

function check_system {

	okay=0

	# Check whether libvirtd is running
	eval $(systemctl show libvirtd -p ActiveState,SubState 2>/dev/null)
	if [ "$ActiveState" != active -o "$SubState" != "running" ]; then
		echo "The libvirtd service does not seem to be running; please activate it:" >&2
		echo "  systemctl start libvirtd" >&2
		okay=1
	fi

	# Should we check anything else?

	return $okay
}

function cleanup_domain {

	local vm_name=$1

	virsh dominfo "$vm_name" >/dev/null 2>&1 || return 0

	echo
	echo "A domain named $vm_name already exists"
	virsh dominfo "$vm_name"
	virsh domblklist "$vm_name"
	echo

	if ! $opt_force; then
		user_confirm "Destroy this VM and its storage?" || exit 1
	fi

	if virsh dominfo "$vm_name" | grep -qs State.*running; then
		echo "Shutting down $vm_name"
		virsh destroy $vm_name
	fi

	if virsh dominfo "$vm_name" >/dev/null 2>&1; then
		echo "Destroying $vm_name and associated storage"
		virsh undefine --nvram --remove-all-storage $vm_name
	fi

	# Instead of --remove-all-storage:
	# virsh vol-delete --pool default $vm_name.qcow2
	return 0
}

function install_from_disk {

	local vm_name=$1
	local golden_image=$2

	suffix=${golden_image//*.}

	local image="$opt_cache_dir/$vm_name.$suffix"
	if [ -f "$image" ]; then
		if ! $opt_force; then
			user_confirm "A VM image named $image already exists. Remove?" || exit 1
		fi
		rm -f "$image"
	fi

	cp -v "$golden_image" "$image" || exit 1

	case "$(virsh net-info default | grep -i active)" in
	*yes*) : ;;
	*)
		echo "Starting libvirt network \"default\""
		virsh net-start default;;
	esac

	# For as long as the packages in SUSE:ALP aren't signed with a recognized key,
	# we need this:
	UEFI_CODE_FILE="/usr/share/qemu/ovmf-x86_64-smm-opensuse-code.bin"
	UEFI_VARS_FILE="/usr/share/qemu/ovmf-x86_64-smm-opensuse-vars.bin"
	if [ "$opt_sb_auth" = "alp" ]; then
		echo "Using UEFI variables image $UEFI_ALP_VARS_FILE" >&2
		UEFI_VARS_FILE="$UEFI_ALP_VARS_FILE"
	fi

	extra_options=""
	if ! $opt_persistent; then
		extra_options+=" --transient"
	fi

	set -x
	exec virt-install --name $vm_name \
		--os-variant="$ALP_OS_VARIANT" \
		--boot "hd" \
		--features smm=on \
		--boot "loader=$UEFI_CODE_FILE,loader_ro=yes,loader_type=pflash,loader_secure=yes,nvram_template=$UEFI_VARS_FILE" \
		--import \
		--disk $image,bus=sata \
		--memory 2048 \
		--console pty,target_type=virtio \
		--tpm backend.type=emulator,backend.version=2.0,model=tpm-tis \
		--network network=default \
		$extra_options \
		--autoconsole graphical
}

mkdir -p "$opt_cache_dir"

case $# in
0)	
	download_image;;
1)	ALP_IMG_LOCAL=$1; shift;;
*)	echo "Too many arguments" >&2
	usage 1;;
esac



check_system || exit 1
cleanup_domain $opt_vm_name
install_from_disk $opt_vm_name $ALP_IMG_LOCAL

